# Generated by Django 6.1.1 on 2026-09-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banner')),
                ('button_link', models.CharField(max_length=122)),
                ('button_text', models.CharField(max_length=122)),
                ('sort_order', models.CharField(max_length=122)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
