# Generated by Django 6.1.1 on 2026-09-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_material_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='ProductMaterial',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_product.subcategory'),
        ),
        migrations.RenameModel(
            old_name='product_color',
            new_name='ProductColor',
        ),
        migrations.RenameModel(
            old_name='product_size',
            new_name='ProductSize',
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_product.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_product.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_product.productsize')),
            ],
        ),
        migrations.DeleteModel(
            name='product_options',
        ),
    ]
